# Generated by Django 5.2.12 on 2026-03-13 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0001_initial'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=64, unique=True)),
                ('out_type', models.CharField(choices=[('sale', '销售出库'), ('use', '领用出库'), ('scrap', '报废出库')], max_length=32)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending', '待审核'), ('frozen', '已冻结'), ('done', '已出库'), ('cancelled', '作废')], default='draft', max_length=32)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('audit_time', models.DateTimeField(blank=True, null=True)),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'out_order',
            },
        ),
        migrations.CreateModel(
            name='OutDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.CharField(blank=True, max_length=64, null=True)),
                ('req_qty', models.IntegerField()),
                ('frozen_qty', models.IntegerField(default=0)),
                ('actual_qty', models.IntegerField(default=0)),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.goods')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.warehouse')),
            ],
            options={
                'db_table': 'out_detail',
            },
        ),
    ]
