# Generated by Django 5.2.12 on 2026-03-13 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0001_initial'),
        ('inbound', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inorder',
            name='audit_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audited_in_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inorder',
            name='create_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_in_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inorder',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='goods.supplier'),
        ),
        migrations.AddField(
            model_name='indetail',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='inbound.inorder'),
        ),
    ]
