# Generated by Django 5.2.12 on 2026-03-13 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='仓库名称')),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('manager', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'verbose_name': '仓库',
                'verbose_name_plural': '仓库',
                'db_table': 'warehouse',
            },
        ),
    ]
